export const STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Orissa",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export const TARGET_BASE =
  "https://facilities.aicte-india.org/dashboard/pages/php/approvedinstituteserver.php";

export const DEFAULT_UPSTREAM_PARAMS: Record<string, string> = {
  method: "fetchdata",
  year: "2025-2026",
  program: "1",
  level: "1",
  institutiontype: "1",
  Women: "1",
  Minority: "1",
  state: "Tamil Nadu",
  course: "1",
};

export const DEFAULT_ROW_FIELDS = [
  "aicte_id",
  "institute_name",
  "address",
  "district",
  "institution_type",
  "women",
  "minority",
  "other_id",
] as const;
